apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-front
  namespace: ace-official
  labels:
    app: events
    tier: frontend
    service: web
spec:
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: events-front
  template:
    metadata:
      labels:
        app: events-front
        tier: frontend
        service: web
    spec:
      containers:
        - name: events-front
          image: quay.io/uface/events-front:0.3.0
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-back
  namespace: ace-official
  labels:
    app: events
    tier: backend
    service: web
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: events-back
  template:
    metadata:
      labels:
        app: events-back
        tier: backend
        service: web
    spec:
      containers:
        - name: events-back
          image: quay.io/uface/events-back:0.1.0
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PG_HOST
              value: event-db
            - name: PG_DATABASE
              value: events
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: event-db-auth
                  key: POSTGRES_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-db-auth
                  key: POSTGRES_PASSWORD
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: events-back
                  key: SECRET_KEY_BASE
      initContainers:
        - name: events-db-init
          image: quay.io/uface/events-db-init:0.1.0
          env:
            - name: PG_HOST
              value: event-db
            - name: PG_DATABASE
              value: events
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: event-db-auth
                  key: POSTGRES_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-db-auth
                  key: POSTGRES_PASSWORD 
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: events-back
                  key: SECRET_KEY_BASE
---
apiVersion: v1
kind: Service
metadata:
  name: events-front
  namespace: ace-official
  labels:
    service: web
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: events-front
---
apiVersion: v1
kind: Service
metadata:
  name: events-back
  namespace: ace-official
  labels:
    service: web
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: events-back
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: events
  namespace: ace-official
  labels:
    service: web
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - uf-ace.com
        - www.uf-ace.com
      secretName: home-tls
  rules:
    - host: uf-ace.com
      http:
        paths:
          - path: /events/
            backend:
              serviceName: events-front
              servicePort: 80
          - path: /events/auth
            backend:
              serviceName: events-back
              servicePort: 80
          - path: /events/api
            backend:
              serviceName: events-back
              servicePort: 80
    - host: www.uf-ace.com
      http:
        paths:
          - path: /events/
            backend:
              serviceName: events-front
              servicePort: 80
          - path: /events/auth
            backend:
              serviceName: events-back
              servicePort: 80
          - path: /events/api
            backend:
              serviceName: events-back
              servicePort: 80